services:
  db:
    build: ./app/bdd
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: counterdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - monReseau

  app-flask:
    build: ./app
    container_name: app-flask
    restart: always
    networks:
      - monReseau
    depends_on:
      - db

  phpmyadmin:
    build: ./app/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: user
      PMA_PASSWORD: password
    networks:
      - monReseau
    depends_on:
      - db

  calculatrice:
    build: ./web
    container_name: calculatrice
    networks:
     - monReseau

  tests:
    build: ci
    container_name: tests
    depends_on:
      - calculatrice
      - app-flask
    networks:
      - monReseau

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    networks:
      - monReseau
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - calculatrice
      - app-flask
      - phpmyadmin

volumes:
  mysql_data:
networks:
  monReseau:
