services:
  db:
    build: ./app/bdd
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: counterdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - monReseau

  app-flask:
    build: ./app
    container_name: app-flask
    restart: always
    ports:
      - "5000:5000"
    networks:
      - monReseau
    depends_on:
      - db

  phpmyadmin:
    build: ./app/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: user
      PMA_PASSWORD: password
    ports:
      - "8081:80"
    networks:
      - monReseau
    depends_on:
      - db

  calculatrice:
    build: ./web
    container_name: calculatrice
    ports:
      - "8080:80"
    networks:
     - monReseau

  tests:
    build: ci
    container_name: tests
    depends_on:
      - calculatrice
      - app-flask
    networks:
      - monReseau



volumes:
  mysql_data:
networks:
  monReseau:
